### ISSUE TITLE
Boot2docker with containers `/etc/hosts` updated to point localhost to other containers

### ISSUE THREAD

**Issue by Oliboy50** [docker/machine#1417]
When I used `boot2docker` to run a development environment using Docker (on Windows), I was able to link several containers and let them talk between them with the IP `127.0.0.1`. But it seems that Docker Machine does not behave the same.

Let's say my application is composed of 2 containers: **container WEB** and **container DB**.

Using `boot2docker`, I was able to make **container WEB** talking to **container DB** with IP `127.0.0.1`.

Using `docker-machine -d virtualbox`, I can't use `127.0.0.1` anymore, I have to use the dynamic IP generated (somewhere) `172.17.0.11`. (This is not even the `docker-machine ip` which is `192.168.99.100`)

It's now really hard to have a generic default configuration in my **container WEB**...

Maybe @SvenDowideit knows something about how boot2docker did that (I mean pointing localhost to other containers)? Or maybe I dreamed about that feature and it has always been a pain to let several containers talk between them.

Thanks for your help.

Both Boot2Docker.iso version i'm talking about are 1.6.2
Docker Machine version is 0.3.0-rc2

EDIT:

Here is how I link my containers
```
web:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ..:/var/www/html
  links:
    - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_DATABASE: mydb
    MYSQL_ALLOW_EMPTY_PASSWORD: yes

```
