### ISSUE TITLE
Corrupt file rights on host volumes with vmwarefusion driver

### ISSUE THREAD

**Issue by ain** [docker/machine#1789]
Following compose file run under the user `deploy`
```yaml
web:
  image: myimage:latest
  volumes:
    - .:/docker
    - ~/.ssh:/home/deploy/.ssh
```
will result in `/home/deploy/.ssh` mapped as
```
drwxr-xr-x   1    501 dialout 1292 Jul  3 19:36 .ssh
```
