### ISSUE TITLE
Cannot access linked host on osx when building service from path

### ISSUE THREAD

**Issue by nicc** [docker/machine#2059]
Hi there,

I'm running into a problem on osx. Here's my docker-compose.yml file:

```yaml
web:
  build: .
  volumes:
   - .:/srv/service
  links:
   - enrichment-service
  env_file:
   - .env
  ports:
   - "81:80"

enrichment-service:
  build: ../enrichment-service
  # image: enrichment-service
  container_name: enrichment-service
  links:
   - alchemy-service
  environment:
   - ALCHEMY_SERVICE_HOST=http://alchemy-service

alchemy-service:
  image: alchemy-service
  container_name: alchemy-service
```

If I use the image from dockerhub for the enrichment service (commented out line), then everything works fine, but if I build it as per the docker-compose.yml file above, I get `RestClient::ServerBrokeConnection - Server broke connection` from inside the enrichment-service, and I see no log of the request ever reaching alchemy-service.

I've tried mapping the ports explicitly between the services, and updating the endpoints accordingly, but still no luck.

I'm asking this here instead of at docker-compose since it seems to be specific to the docker-machine vm on my mac. Colleagues running ubuntu without docker-machine do not experience these problems.

some further info:
`docker-machine version 0.4.1 (e2c88d6)`
`docker-compose version: 1.4.2`
`Docker version 1.8.3, build f4bf5c7`
`OSX Yosemite 10.10.5`

Any help would be greatly appreciated. Let me know if you need anything else from me.

Thanks,
Nic
