### ISSUE TITLE
Docker won't mount any files unless machine is created by root

### ISSUE THREAD

**Issue by liamawhite** [docker/machine#3255]
I've raised the issue here as I believe it is a docker-machine issue. Its also highly likely that it is a configuration issue on my part.

When trying to mount directories and files into my interlock container it fails to find the files so it creates directories in the place of the files and empty directories in place of the directories. The other volume is created as part of the compose YAML and works fine. If I create the machine using sudo and run the rest of the commands using sudo then the YAML works as expected. Should docker-machine be running with root permissions anyway?

docker-machine version 0.6.0, build e27fb87
docker-compose version 1.6.2, build 4d72027
Docker version 1.10.3, build 20f81dd

```
version: '2'

services:
    interlock:
        image: ehazlett/interlock:ng
        container_name: interlock
        command: run
        ports:
            - 8080
        volumes:
            - ./config.toml:/bin/config.toml
            - nginx:/etc/conf
            - ~/.docker/machine/certs:/certs/
```
