### ISSUE TITLE
Mounting the default virtualbox instance makes volumes unreachable

### ISSUE THREAD

**Issue by PJEstrada** [docker/machine#3751]
I have a docker-compose file where I put a volume to run an ansible playbook.

```
agent:
  image: pjestrada/ansible
  volumes:
    - ../../ansible/probe.yml:/ansible/site.yml
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"
```

The file works great when I dont have my docker machine up. But as soon as I run my default docker-machine created with:
`docker-machine create --driver virtualbox default`
and use eval to set the env variables.

I run again:
docker-compose up agent

and get this error:
```
agent_1 | ERROR! the playbook: site.yml does not appear to be a file
dev_agent_1 exited with code 1
```

I think there must be some kind of problem with the filesystem when the virtualbox default driver. Im on Ubuntu 16.04 LTS
