### ISSUE TITLE
docker-machine ssh myvm1 in tutorial Part 4 returns `unexpected end of file`

### ISSUE THREAD

**Issue by jmvbxx** [docker/machine#4303]
I working through the tutorial and in part 4 and I get the following:
```
$ docker-machine ssh myvm1 "docker swarm init --advertise-addr <myvm1 ip>"
sh: syntax error: unexpected end of file
exit status 2
```
Versions:
`docker-machine version 0.12.2, build 9371605`
`Docker version 17.09.0-ce, build afdb6d4`
`Ubuntu 16.04.3 LTS`

Docker compose file:
```
version: "3"
services:
  web:
    image: jemops/get-started:part2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
```

Thank you in advance!
