### ISSUE TITLE
Option to create DNS record on Droplet creation

### ISSUE THREAD

**Issue by iBobik** [docker/machine#4647]
Will be handy to have option on create command what will create A record in DO DNS hosting pointing to this new machine.

It will be helpful in automation, e.g. CI can create machine with specified hostname including branch name. In GitLab CI it could looks like:
```yaml
deploy review:
  image: tmaier/docker-compose
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://${CI_ENVIRONMENT_SLUG}.${CI_PROJECT_NAME}.$REVIEW_DOMAIN
  script:
    - docker-machine create --driver digitalocean --do-dns-record ${CI_ENVIRONMENT_SLUG}.${CI_PROJECT_NAME}.$REVIEW_DOMAIN ${CI_ENVIRONMENT_SLUG}.${CI_PROJECT_NAME}
    - docker-compose up -d
  only:
    refs:
      - branches
```
